### ISSUE TITLE
User interface and new features 

### ISSUE THREAD

**Issue by nitin-787** [hadikachmar3/chatGPT_flutter_course#2]
Greetings, sir. I am currently working on a school project and have independently created the user interface. Would it be possible for you to review it? It would be greatly appreciated if we could incorporate the user interface into the project.
Additionally, I have many innovative ideas regarding this application. Therefore, I would like to propose the possibility of collaborating with you. Working together could lead to a more comprehensive and effective final product.

**Comment by hadikachmar3** [comment]
Hello,

I'm sorry, but I am very limited with my time. I don't have time to review private projects, but if you create something interesting that may be added to this project, you can contact me through my Facebook page and I'll add you as a contributor.

I'll close this thread since I don't think that this should be posted as a GitHub issue.

Regards,
Hadi.

**Comment by RageshAntony** [comment]
@hadikachmar3 
I have added Chat memory feature that is as per current implementation, it could not remember previous chat like...
```

User : Hi Ragesh and I am living in Tamil Nadu
Assistent: Hi Ragesh, Nice to meet to you  ? How is your life in Tamil Nadu?
User: Tell me somethings about my name and current place ?
Assistant: As a AI lanuage model , I don't know your name and current place...........Please provide them now....
```


Now After my current implementation
 
<img width="372" alt="image" src="https://user-images.githubusercontent.com/36100215/228177631-3085074f-e211-4484-a6de-f35dfdc65134.png">

So, could I create an PR ?

**Comment by nitin-787** [comment]
hey @RageshAntony https://github.com/nitin-787/Ayumi-gpt wanna work on the same project ?

**Comment by hadikachmar3** [comment]
Hello @RageshAntony, yes you may request, you can reach me on [Discord](https://discord.gg/gycactGhKH) or [my Facebook page](https://www.facebook.com/people/Coding-with-Hadi/100071826750087/) to discuss further.

**Comment by RageshAntony** [comment]
@hadikachmar3 Thanks very much.

 Created a pull request. Please review 
https://github.com/hadikachmar3/ChatGPT_flutter_course/pull/3

**Comment by RageshAntony** [comment]
@nitin-787 

Let me clone and examine it. Happy to contribute if I able to
