### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by limcheekin** [hadikachmar3/chatGPT_flutter_course#4]
Thanks for sharing the codes.

Please add a LICENSE file to the repo so that it is clear the codes released under what licensing terms.

Thank you.

**Comment by hadikachmar3** [comment]
Hello, I added MIT LICENSE.

**Comment by limcheekin** [comment]
Thanks. I incorporated your codes into Fluwix. You can find out more at https://limcheekin.blogspot.com/2023/04/flutter-chatbot-ui.html
