### ISSUE TITLE
can't load google ads on this particular project

### ISSUE THREAD

**Issue by rkindustriesYT** [hadikachmar3/chatGPT_flutter_course#6]
RewardedAd failed to load: LoadAdError(code: 3, domain: com.google.android.gms.ads, message: No fill., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: , adapterResponses: [], loadedAdapterResponseInfo: null), responseExtras: {})

this is the error i am getting while implementing google ads in this project but when i use same ad loading code to any projects other than this works fine

**Comment by hadikachmar3** [comment]
Hello @rkindustriesYT , loading ads shouldn't be a problem. it should be okay to add ads to the app.

**Comment by rkindustriesYT** [comment]
It was a problem but anyhow i figured it out the,I am 100% sure that the  problem was app name chatgpt, when i changed that everything works fine
